#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

"$DIR/php-scoper/vendor/bin/php-scoper" add-prefix --working-dir="$DIR" --output-dir=relocated &&
composer --working-dir="$DIR/relocated" --classmap-authoritative dumpautoload
